### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by rohit-gohri** [smartprix/babel-changed#3]
For a simple CLI it depends on lots of unneeded dependencies due to sm-utils. Until https://github.com/smartprix/sm-utils/issues/33 happens it would be better to use glob and bluebird instead of File and Vachan respectively.

This would have the added benefit of faster execution time when using `npx @smpx/babel-changed`.

**Comment by hit12369** [comment]
Yeah, `sm-utils` is not really necessary here. I'll work on it.
