### ISSUE TITLE
Ignore glob

### ISSUE THREAD

**Issue by mocanew** [smartprix/babel-changed#7]
Using `ignore-glob` cli argument leads to high execution time because the first 2 glob calls in `transform` scan the ignored folders.

In my case, I wanted to ignore `node_modules` and I think it's a standard use-case. Maybe the default `--file-glob` could be changed to `--file-glob \"{,!(node_modules)/**/}*.*\"` or this pattern could have a section in readme.
The execution time was 2 seconds with the standard glob pattern and <0.1s for the one that ignores node_modules.

> Before parsing the path part patterns, braced sections are expanded into a set. Braced sections start with { and end with }, with any number of comma-delimited sections within. Braced sections may contain slash characters, so a{/b/c,bcd} would expand into a/b/c and abcd. [glob-readme](https://github.com/isaacs/node-glob/blob/v7.1.6/README.md#glob-primer)

The pattern matches:
- `*.*`: files in the src directory
- `!(node_modules)/**/*.*`: files in other directories except node_modules

**Comment by hit12369** [comment]
This does not work for nested `node_modules`. I'll replace `glob` with `fast-glob` that has the feature to specify ignore pattern.
